spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

cloud:
  aws:
    region: "us-east-1"
    credentials:
      accessKeyId: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_ACCESS_KEY_SECRET}
    sqs:
      name: "store-api"
    ses:
      email: ${AWS_SES_EMAIL}
    dynamodb:
      endpoint: "https://dynamodb.us-east-1.amazonaws.com"

server:
  error:
    include-message: always
  servlet:
    contextPath: /api

auth:
  jwt:
    secretKey: ${JWT_SECRET_KEY}
    issuer: ${JWT_ISSUER}
    expiration: 86400000