spring:
  datasource:
    url: "jdbc:h2:mem:authentication"
    driverClassName: org.h2.Driver
    username: "user"
    password: "pass"
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.H2Dialect"
    hibernate:
      ddl-auto: "update"
  h2:
    console:
      enabled: false

  server:
    port: 8000
    error:
      include-message: always
    servlet:
      contextPath: /api