spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

server:
  error:
    include-message: always
  servlet:
    contextPath: /api

auth:
  jwt:
    secretKey: "4Z^XrroxR@dWxqf$mTTKwW$!@#qGr4P"
    issuer: "pizzurg-api"
    expiration: 86400000