CREATE SCHEMA IF NOT EXISTS AUTHENTICATION;

CREATE TABLE AUTHENTICATION.USERS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255),
    EMAIL VARCHAR(255) UNIQUE,
    USERNAME VARCHAR(255) UNIQUE,
    PASSWORD VARCHAR(255),
    ROLE VARCHAR(50)
);