CREATE SCHEMA IF NOT EXISTS STORE;

CREATE TABLE IF NOT EXISTS STORE.CASHIER (
    ID SERIAL PRIMARY KEY,
    TRANSACTION_TYPE VARCHAR(50) NOT NULL,
    PAYMENT_TYPE VARCHAR(50) NOT NULL,
    VALUE NUMERIC(10, 2) NOT NULL,
    AMOUNT INTEGER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    COMMENTS TEXT
);