name: CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build project
        run: mvn clean install -DskipTests

      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build docker image
        run: docker build -t lucasgraciano/.

      - name: Push image docker
        run: docker push lucasgraciano/spring-security-auth-api

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull lucasgraciano/spring-security-auth-api:latest
      - name: Remove docker container
        run: docker rm -f deploy_ghactions
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name spring-security-auth-api lucasgraciano/spring-security-auth-api
