name: CI Pipeline
on:
  pull_request:
    branches:
      - 'main'

  push:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build project
        run: mvn -B package --file pom.xml

      - name: Execute tests
        run: mvn test --file pom.xml